# Generated by Django 5.2 on 2025-10-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinhanh', models.TextField(blank=True, null=True)),
                ('masp', models.CharField(max_length=255)),
                ('tensp', models.CharField(max_length=255)),
                ('mota', models.TextField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('madanhmuc', models.CharField(max_length=255)),
                ('mathuonghieu', models.CharField(blank=True, max_length=255, null=True)),
                ('gioitinh', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
